version: "3.9"
services:
  usuarioService:
    container_name: ms-usuario
    image: ms-usuario:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - network_tp
networks:
  network_tp:
    driver: bridge